Add decrease tests for oracle token
skmgoldin/EIP621Token pull request #1
Opened 2017-08-02 17:39 UTC by Peam35

2017-08-02 19:12 UTC, skmgoldin commented
Hi Kareem, thank you for this excellent pull request. Could you make these changes before we merge it?

1. Your test `it('Should increase supply by 10 then decrease by 4'` is misspecified. It should say `it('Should increase supply by 10 then decrease by 6'`
2. In your test `it('Should increase the supply by 10 and fail to decrease it by 11'`, please use the `asOracle` function idiomatically.
3. Could you use `increaseAmount` and `decreaseAmount` like in the existing tests?

Thanks Kareem! Can't wait to merge this!

2017-08-02 19:47 UTC, Peam35 commented
Hey Mike! All the problems are fixed now (I hope)

2017-08-08 15:05 UTC, skmgoldin requested changes
Just one change, then I'll merge!

2017-08-08 15:05 UTC, skmgoldin commented on test/eip621OraclizedToken.js
> +        const expectedSupply = (initialAmount + (increaseAmount - decreaseAmount)).toString()
You already computed `increaseAmount - decreaseAmount` on line 47, so just use `amountFinal` here.

2017-08-08 15:08 UTC, skmgoldin approved these changes

2017-08-08 15:16 UTC, merged